stages:
  - build
variables:
  BUILD_TAG: django-app:${CI_COMMIT_SHORT_SHA}
build-docker-compose:

  tags:
    - ivan-shell
    - shell
  script:
    - docker compose build
  stage: build
  only:
    - master
    - merge_requests

